FROM eclipse-temurin:17

LABEL maintainer="tt2703633@gmail.com"

WORKDIR /app

COPY target/userRegistersystem-0.0.1-SNAPSHOT.jar /app/user-register-system.jar

ENTRYPOINT ["java", "-jar", "user-register-system.jar"]
